# Generated by Django 3.2.9 on 2021-12-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=8, unique=True)),
                ('ticker', models.CharField(default='', max_length=5, unique=True)),
            ],
        ),
    ]
