# Generated by Django 3.2.9 on 2021-12-03 18:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=api.models.generate_uid, max_length=8, unique=True)),
                ('ticker', models.CharField(default='', max_length=5, unique=True)),
                ('company', models.CharField(default='', max_length=126, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
