# Generated by Django 3.2.9 on 2021-12-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211203_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
