# Generated by Django 3.2.9 on 2021-12-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_watchlist_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprofile',
            name='uid',
        ),
        migrations.AddField(
            model_name='stockprofile',
            name='closing_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stockprofile',
            name='company',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockprofile',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stockprofile',
            name='industry',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='stockprofile',
            name='market_cap',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stockprofile',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='stockprofile',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='stockprofile',
            name='sector',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='stockprofile',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockprofile',
            name='ticker',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
