# Generated by Django 3.2.9 on 2021-12-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211203_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_field', models.IntegerField(blank=True, db_column='No.', null=True)),
                ('ticker', models.TextField(blank=True, db_column='Ticker', null=True)),
                ('company', models.TextField(blank=True, db_column='Company', null=True)),
                ('sector', models.TextField(blank=True, db_column='Sector', null=True)),
                ('industry', models.TextField(blank=True, db_column='Industry', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('market_cap', models.TextField(blank=True, db_column='Market_Cap', null=True)),
                ('p_e', models.TextField(blank=True, db_column='P/E', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('change', models.TextField(blank=True, db_column='Change', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'overview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_field', models.IntegerField(blank=True, db_column='No.', null=True)),
                ('ticker', models.TextField(blank=True, db_column='Ticker', null=True)),
                ('market_cap', models.TextField(blank=True, db_column='Market_Cap', null=True)),
                ('p_e', models.TextField(blank=True, db_column='P/E', null=True)),
                ('fwd_p_e', models.TextField(blank=True, db_column='Fwd_P/E', null=True)),
                ('peg', models.TextField(blank=True, db_column='PEG', null=True)),
                ('p_s', models.TextField(blank=True, db_column='P/S', null=True)),
                ('p_b', models.TextField(blank=True, db_column='P/B', null=True)),
                ('p_c', models.TextField(blank=True, db_column='P/C', null=True)),
                ('p_fcf', models.TextField(blank=True, db_column='P/FCF', null=True)),
                ('eps_this_y', models.TextField(blank=True, db_column='EPS_this_Y', null=True)),
                ('eps_next_y', models.TextField(blank=True, db_column='EPS_next_Y', null=True)),
                ('eps_past_5y', models.TextField(blank=True, db_column='EPS_past_5Y', null=True)),
                ('eps_next_5y', models.TextField(blank=True, db_column='EPS_next_5Y', null=True)),
                ('sales_past_5y', models.TextField(blank=True, db_column='Sales_past_5Y', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('change', models.TextField(blank=True, db_column='Change', null=True)),
                ('volume', models.TextField(blank=True, db_column='Volume', null=True)),
            ],
            options={
                'db_table': 'valuation',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='stockprofile',
            name='company',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofile',
            name='ticker',
            field=models.CharField(max_length=5),
        ),
    ]
